from typing import List, Protocol, runtime_checkable


@runtime_checkable
class AsyncInventoryStorage(Protocol):

    async def aselect(self, item_type: str) -> List[dict]: ...

    async def aread(self, item_type: str, id: str) -> dict: ...

    async def awrite(self, item_type: str, item: dict) -> bool: ...

    async def adelete(self, item_type: str, id: str) -> bool: ...
