from typing import List, Protocol, runtime_checkable


@runtime_checkable
class InventoryStorage(Protocol):

    def select(self, item_type: str) -> List[dict]: ...

    def read(self, item_type: str, id: str) -> dict: ...

    def write(self, item_type: str, item: dict) -> bool: ...

    def delete(self, item_type: str, id: str) -> bool: ...
